function networks() {
  const rows = state.data.networks || [];
  return `${pageHeader("Zielnetze", "Aktive Netze werden in /24-Jobs aufgeteilt und automatisch rotiert.")}
    <section class="panel"><h2>Netz anlegen</h2><div class="form-grid"><label>Name<input id="networkName" value="Produktivnetz"></label><label>CIDR<input id="networkCidr" class="mono" value="192.168.0.0/16"></label><label>Discovery-Intervall (s)<input id="networkInterval" type="number" value="120"></label><label>Deep-Scan-Intervall (min)<input id="networkDeepInterval" type="number" value="360"></label><label>Rate-Limit/min<input id="networkRate" type="number" value="600"></label><label>Scanfenster<input id="networkWindow" placeholder="optional"></label><label class="wide">Ausschlüsse<input id="networkExcludes" class="mono" placeholder="192.168.1.1, 192.168.2.0/24"></label><div class="form-action"><button data-action="create-network">Anlegen</button></div></div></section>
    <section class="panel"><h2>Zielnetze verwalten</h2><div class="settings-list">${rows.map((row) => `<article class="settings-row"><div class="form-grid"><label>Name<input data-id="${h(row.id)}" data-field="network_name" value="${h(row.name || "")}"></label><label>CIDR<input data-id="${h(row.id)}" data-field="network_cidr" class="mono" value="${h(row.cidr || "")}"></label><label>Discovery (s)<input data-id="${h(row.id)}" data-field="network_interval" type="number" value="${h(row.discovery_interval_seconds || 120)}"></label><label>Deep-Scan (min)<input data-id="${h(row.id)}" data-field="network_deep" type="number" value="${h(row.deep_scan_interval_minutes || 360)}"></label><label>Rate-Limit/min<input data-id="${h(row.id)}" data-field="network_rate" type="number" value="${h(row.rate_limit_per_minute || 600)}"></label><label>Scanfenster<input data-id="${h(row.id)}" data-field="network_window" value="${h(row.scan_window || "")}"></label><label class="wide">Ausschlüsse<input data-id="${h(row.id)}" data-field="network_excludes" class="mono" value="${h((row.excludes || []).join(", "))}"></label><label class="checkbox-label">Aktiv<input data-id="${h(row.id)}" data-field="network_active" type="checkbox" ${checked(row.is_active)}></label><div class="row-actions"><button class="small" data-action="save-network" data-id="${h(row.id)}">Speichern</button><button class="danger small" data-action="delete-network" data-id="${h(row.id)}">Löschen</button></div></div></article>`).join("") || emptyState("📡", "Keine Zielnetze", "Lege mindestens ein Zielnetz an.")}</div></section>`;
}

function profiles() {
  const ports = state.data.portProfiles || [];
  const scansData = state.data.scanProfiles || [];
  return `${pageHeader("Profile", "Portlisten und freigabepflichtige Scanarten zentral verwalten.")}
    <section class="panel"><h2>Portprofil anlegen</h2><div class="form-grid"><label>Name<input id="newPortName" value="Standard Discovery"></label><label>Beschreibung<input id="newPortDescription" placeholder="Optionale Beschreibung"></label><label class="wide">Ports<textarea id="newPortPorts">22, 80, 443, 445, 3389, 5000, 8080, 8443, 9100</textarea></label><label class="checkbox-label">Standard<input id="newPortDefault" type="checkbox"></label><div class="form-action"><button data-action="create-port-profile">Anlegen</button></div></div></section>
    <div class="layout-2"><section class="panel"><h2>Portprofile</h2><div class="settings-list">${ports.map((row) => `<article class="settings-row"><label>Name<input data-id="${h(row.id)}" data-field="port_name" value="${h(row.name || "")}"></label><label>Beschreibung<input data-id="${h(row.id)}" data-field="port_description" value="${h(row.description || "")}"></label><label>Ports<textarea data-id="${h(row.id)}" data-field="port_ports">${h((row.ports || []).join(", "))}</textarea></label><label class="checkbox-label">Standard<input data-id="${h(row.id)}" data-field="port_default" type="checkbox" ${checked(row.is_default)}></label><div class="row-actions"><button class="small" data-action="save-port-profile" data-id="${h(row.id)}">Speichern</button><button class="danger small" data-action="delete-port-profile" data-id="${h(row.id)}">Löschen</button></div></article>`).join("") || emptyState("🔌", "Keine Portprofile", "Lege ein Portprofil an.")}</div></section>
    <section class="panel"><h2>Scanprofile</h2><div class="settings-list">${scansData.map((row) => `<article class="settings-row"><label>Name<input data-id="${h(row.id)}" data-field="scan_name" value="${h(row.name || "")}"></label><label>Art<input data-id="${h(row.id)}" data-field="scan_kind" value="${h(row.kind || "")}"></label><label>Konfiguration (JSON)<textarea data-id="${h(row.id)}" data-field="scan_config">${h(JSON.stringify(row.config || {}, null, 2))}</textarea></label><label class="checkbox-label">Aktiviert<input data-id="${h(row.id)}" data-field="scan_enabled" type="checkbox" ${checked(row.is_enabled)}></label><label class="checkbox-label">Manuelle Freigabe<input data-id="${h(row.id)}" data-field="scan_approval" type="checkbox" ${checked(row.requires_manual_approval)}></label><div class="row-actions"><button class="small" data-action="save-scan-profile" data-id="${h(row.id)}">Speichern</button><button class="danger small" data-action="delete-scan-profile" data-id="${h(row.id)}">Löschen</button></div></article>`).join("") || emptyState("🛡", "Keine Scanprofile", "Scanprofile werden serverseitig angelegt oder gebootstrapped.")}</div></section></div>`;
}

function credentialOptions(current = "") {
  const rows = state.data.credentials || [];
  return `<option value="">Keine Zugangsdaten</option>${rows.map((row) => `<option value="${h(row.id)}" ${selected(current, row.id)}>${h(row.name)} (${h(row.type)})</option>`).join("")}`;
}

function identity() {
  const rows = state.data.identitySources || [];
  return `${pageHeader("Quellen", "DHCP, ARP, SNMP, DNS und Discovery-Quellen verbessern die Gerätezuordnung.")}
    <section class="panel"><h2>Quelle hinzufügen</h2><div class="form-grid"><label>Name<input id="sourceName" value="Core Switch SNMP"></label><label>Typ<select id="sourceType"><option value="snmp">SNMP</option><option value="arp">ARP</option><option value="dhcp">DHCP</option><option value="dns">DNS</option><option value="file">Datei</option><option value="ssdp">SSDP</option><option value="mdns">mDNS</option></select></label><label>Host / Pfad<input id="sourceHost" class="mono" placeholder="192.168.1.1 oder /data/leases.csv"></label><label>Zugangsdaten<select id="sourceCredential">${credentialOptions()}</select></label><div class="form-action"><button data-action="create-source">Speichern</button></div></div></section>
    <section class="panel"><h2>Quellen verwalten</h2><div class="settings-list">${rows.map((row) => `<article class="settings-row"><div class="form-grid"><label>Name<input data-id="${h(row.id)}" data-field="source_name" value="${h(row.name || "")}"></label><label>Typ<select data-id="${h(row.id)}" data-field="source_type"><option value="snmp" ${selected(row.type, "snmp")}>SNMP</option><option value="arp" ${selected(row.type, "arp")}>ARP</option><option value="dhcp" ${selected(row.type, "dhcp")}>DHCP</option><option value="dns" ${selected(row.type, "dns")}>DNS</option><option value="file" ${selected(row.type, "file")}>Datei</option><option value="ssdp" ${selected(row.type, "ssdp")}>SSDP</option><option value="mdns" ${selected(row.type, "mdns")}>mDNS</option></select></label><label>Host / Pfad<input data-id="${h(row.id)}" data-field="source_target" class="mono" value="${h(row.config?.host || row.config?.path || "")}"></label><label>Zugangsdaten<select data-id="${h(row.id)}" data-field="source_credential">${credentialOptions(row.credential_id || row.config?.credential_id)}</select></label><label class="checkbox-label">Aktiv<input data-id="${h(row.id)}" data-field="source_active" type="checkbox" ${checked(row.is_active)}></label><div class="row-actions"><button class="small" data-action="save-source" data-id="${h(row.id)}">Speichern</button><button class="secondary small" data-action="test-source" data-id="${h(row.id)}">Test</button><button class="secondary small" data-action="sync-source" data-id="${h(row.id)}">Sync</button><button class="danger small" data-action="delete-source" data-id="${h(row.id)}">Löschen</button></div></div></article>`).join("") || emptyState("⊛", "Keine Quellen", "Lege Quellen für eine bessere Geräteidentität an.")}</div></section>`;
}

function credentials() {
  const rows = state.data.credentials || [];
  return `${pageHeader("Zugangsdaten", "Verschlüsselte Profile für SNMP, SSH, WinRM, HTTP und API-Tokens.")}
    <section class="panel"><h2>Profil anlegen</h2><div class="form-grid credentials-form"><label>Name<input id="credName" value="Switch SNMP read-only"></label><label>Typ<select id="credType"><option value="snmp">SNMP</option><option value="ssh">SSH</option><option value="winrm">WinRM</option><option value="api_token">API Token</option><option value="basic_auth">HTTP Basic</option></select></label><label>Benutzer<input id="credUsername" placeholder="optional"></label><label>Host<input id="credHost" class="mono" placeholder="optional, für Tests"></label><label>Passwort / Token<input id="credSecret" type="password"></label><label>SNMP Community<input id="credCommunity" type="password"></label><label class="wide">Zielmuster<input id="credTargets" class="mono" placeholder="192.168.1.0/24, switch"></label><div class="form-action"><button data-action="create-credential">Speichern</button></div></div></section>
    <section class="panel"><h2>Profile verwalten</h2><div class="settings-list">${rows.map((row) => `<article class="settings-row"><div class="form-grid"><label>Name<input data-id="${h(row.id)}" data-field="cred_name" value="${h(row.name || "")}"></label><label>Typ<select data-id="${h(row.id)}" data-field="cred_type"><option value="snmp" ${selected(row.type, "snmp")}>SNMP</option><option value="ssh" ${selected(row.type, "ssh")}>SSH</option><option value="winrm" ${selected(row.type, "winrm")}>WinRM</option><option value="api_token" ${selected(row.type, "api_token")}>API Token</option><option value="basic_auth" ${selected(row.type, "basic_auth")}>HTTP Basic</option></select></label><label>Benutzer<input data-id="${h(row.id)}" data-field="cred_username" value="${h(row.username || "")}"></label><label>Host<input data-id="${h(row.id)}" data-field="cred_host" class="mono" value="${h(row.config?.host || "")}"></label><label>Neues Secret<input data-id="${h(row.id)}" data-field="cred_secret" type="password" placeholder="leer = beibehalten"></label><label>Zielmuster<input data-id="${h(row.id)}" data-field="cred_targets" class="mono" value="${h((row.target_patterns || []).join(", "))}"></label><label class="checkbox-label">Aktiv<input data-id="${h(row.id)}" data-field="cred_active" type="checkbox" ${checked(row.is_active)}></label><div class="row-actions"><button class="small" data-action="save-credential" data-id="${h(row.id)}">Speichern</button><button class="secondary small" data-action="test-credential" data-id="${h(row.id)}">Test</button><button class="danger small" data-action="delete-credential" data-id="${h(row.id)}">Deaktivieren</button></div></div><small>Secrets vorhanden: ${h((row.has_secret_fields || []).join(", ") || "keine")}</small></article>`).join("") || emptyState("⊕", "Keine Profile", "Speichere zentrale Zugangsdatenprofile.")}</div></section>`;
}

